version: '3'
services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    ports:
      - '8000:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${DB_USER}
      DB_MYSQL_PASSWORD: ${DB_PASS}
      DB_MYSQL_NAME: ${DB_NAME}
    volumes:
      - npm_data:/data
      - /opt/npm/ssl:/etc/letsencrypt
  db:
    image: 'docker.io/jc21/mariadb-aria:latest'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - /opt/npm/db:/var/lib/mysql

volumes:
  npm_data:
